config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'welcome#home'
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/user.rb
class User < ActiveRecord::Base
	validates :First_name, presence: true, length: {minimum: 3, maximum: 30}
	validates :Last_name, presence: true, length: {minimum: 3, maximum: 30}
	validates :Email, presence: true, length: {minimum: 10, maximum: 50}
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	
	def index
		@user = User.all
	end

	def new
		@user = User.new

	end

	def edit
		@user = User.find(params[:id])

	end

	def create
		
		@user = User.new(user_params)
		if @user.save
		redirect_to user_path(@user)
	else
		render 'new'
	end
end
     def update
     	@user = User.find(params[:id])
     	if @user.update(user_params)
     		redirect_to user_path(@user)
     	else
     		render 'edit'

     end
     	
     end

	def show
		@user = User.find(params[:id])
	end

	 def destroy
    @user = User.find(params[:id])
    @user.destroy
    
    redirect_to users_path
  end


	private 
	def set_user
     @user = User.find(params[:id])
   end
    def user_params
		params.require(:user).permit(:First_name, :Last_name, :Email)
	end

end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController

	def home
		
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Users</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/edit.html.erb
<h1> Edit user </h1>

<%= form_for @user do |f| %>

<p>
<%= f.label :First_name %> <br/> 
<%= f.text_field :First_name %>
</p>

<p>
<%=f.label :Last_name %> <br/>
<%= f.text_field :Last_name %>
</p>

<p>
<%=f.label :Email %> <br/>
<%= f.text_field :Email %>
</p>

<p>
<%=f.submit %>
</p>

<%= link_to "User listing", users_path %>
<% end %>

app/views/users/index.html.erb

<h1>Listing all user</h1>

<%= link_to "Create new user", new_user_path %> | <%= link_to "Back", root_path %>
<table>
<tr>
	<th>First name |</th> 
	<th>Last name |</th> 
	<th>Email</th>

</tr>

<% @user.each do |user| %>

<tr>
	<td><%= user.First_name %></td>
	<td><%= user.Last_name %></td>
	<td><%= user.Email %></td>
	<td><%= link_to 'Edit |', edit_user_path(user) %> 
	<td><%= link_to ' Delete', user_path(user), method: :delete, data: {confirm: "Are you sure?"} %></td>
	

</tr>
<% end %>
</table>

app/views/users/new.html.erb
<h1> New user </h1>

<%= form_for @user do |f| %>

<p>
<%= f.label :First_name %> <br/> 
<%= f.text_field :First_name %>
</p>

<p>
<%=f.label :Last_name %> <br/>
<%= f.text_field :Last_name %>
</p>

<p>
<%=f.label :Email %> <br/>
<%= f.text_field :Email %>
</p>

<p>
<%=f.submit %>
</p>

<%= link_to "User listing", users_path %>
<% end %>

app/views/users/show.html.erb
<h1> Showing selected user</h1>
<p>
 First name: <%= @user.First_name %>
</p>
<p>
Last name: <%= @user.Last_name %>
</p>
<p>
Email: <%= @user.Email %>
</p>
	<div class="user-actions">
		<%= link_to "Edit this user ", edit_user_path(@user) %> |<%= link_to "Delete this user ", user_path(@user), method: :delete, data: {confirm: "Are you sure you want to delete the article?"} %> | <%= link_to "User listing ", users_path %>  
	</div>

app/views/welcome/home.html.erb
<h1>Users</h1>
<p>
<%= link_to "Create a user", new_user_path %> | <%= link_to "User listing", users_path %>
</p>